# Kinetics: determining Rates for chemical and biochemical reactions

## Remembering Elementary Reactions

Remember from Chapter 1 that if a reaction is elementary we can write the rate 
of this reaction based on its stoichiometry. 

Here, we will make use of this concept to make mathematical models quantifying the kinetics (or reaction rate equations) of complex chemical reactions as well as simple and complex enzymatic reaction. In later chapters we will also apply the ideas developed here to model cells growing in a bioreactor. But before we do that let's discuss some properties of elementary reactions.

What assumptions can we make to help us propose elementary reactions? What arethe rules/properties of elementary reactions?

1. An elementary reaction---a single-step, molecular level event---must be simple. It likely only involves two molecules, as termolecular collisions are very unlikely, and such collisions happening in the correct orientation are even less likely. We can also assume very few bonds will be formed or broken in a single step. 

2. Elementary reactions cannot involve fractional molecules. 

3. Elementary reactions must obey the principle of microscopic reversibility. Microscopic reversibility means that the reaction must follow the same mechanism in the forward and reverse directions. This means that an elementary reaction must be elementary in both directions. 

### Example of an elementary reaction 

As an example of an elementary reaction let's consider the decomposition of ozone:
$$ \require{mhchem}\ce{O3 -> O2 + O^.} $$
In reality, ozone does not decompose spontaneously, ozone collides with an dioxygen and the energy of this collision drives decomposition. Thus the reaction written above is not elementary, because it is not written exactly how the reaction happens at the molecular level. We can write the elementary reaction as:
$$ \require{mhchem}\ce{O3 + O2 -> O2 + O2 + O^.} $$
This equation and that above are both stoichiometrically correct, but the later equation describes the elementary reaction. How do we know this is the elementary reaction? From the rate equation. Fitting experimental data on the decomposition of ozone to the equation for the elementary reaction, $-r_{O_3} = kC_{O_3}C_{O_2}$, yields a much better fit than $-r_{O_3} = kC_{O_3}$. We will discuss fitting reaction data to rate equations later on. 

**This iterative process of hypothesizing elementary reactions, based on plausible reaction mechanisms, and fitting experimental data to rate equations derived from these elementary reactions is the basis of chemical and biochemical kinetics.** 

With this framework for writing elementary reactions in place we can now begin deriving mechanisms and rate equations for more complex reactions, which are actually series of multiple elementary reactions. Let's look at another more complex example of how a stoichiometrically simple reaction can be broken down into elementary reactions by hypothesizing a mechanism.

## Elementary Reactions Provide Feasible Mechanisms

Most seemingly simple reactions are not elementary as written but can be broken down into a sequence of elementary reactions. Take for example the Haber-Bosch process, by which most nitrogen for fertilizer is fixed from the atmosphere. 
$$ \require{mhchem}\ce{N2 + 3H2 <=> 2NH3} $$

#### ???Questions??? 

How many molecules are involved in the forward and reverse reactions?
How many bonds are formed/broken in the forward and reverse reactions? Is this reaction likely elementary as written? Why or why not? 

```{answer, include=params$key, }
>*In the forward reaction 4 species are required to interact simultaneously, which is very unlikely. In the reverse reaction only two species must interact. In the forward reaction 4 bonds must be broken and 6 bonds must be formed, and the opposite is true for the reverse. No, this reaction is not likely elementary as written as the complex interactions and bond rearrangments are highly unlikely in a single step.*
```  

***  

So how does this reaction happen? The Haber-Bosch process relies on a iron catalyst, which facilitates much of this bond breaking and forming by allowing hydrogen and nitrogen species to interact with the catalyst. Let's call the catalyst here $\require{mhchem}\ce{S}$ for solid catalyst. $\require{mhchem}\ce{S^*}$ will represent a open binding site on the catalyst surface. Now let's write elementary reactions that may constitute a mechanism for the Haber-Bosch process. Initially $\require{mhchem}\ce{H2}$ and $\require{mhchem}\ce{N2}$ will adsorb onto the catalyst surface. 
$$ \require{mhchem}\ce{H2 + 2S^* <=> 2H-S^*} $$
$$ \require{mhchem}\ce{N2 + 2S^* <=> 2N-S^*} $$
These forward reactions appear to involve three species, however as our catalyst is solid $\require{mhchem}\ce{2S^*}$ act as essentially a single species. Now to form ammonia these adsorbed species must react. 
$$ \require{mhchem}\ce{ N-S^* + H-S^* <=> NH-S^* + S^*} $$
$$ \require{mhchem}\ce{ NH-S^* + H-S^* <=> NH2-S^* + S^*} $$
$$ \require{mhchem}\ce{ NH2-S^* + H-S^* <=> NH3-S^* + S^*} $$
And finally the ammonia must desorb from the surface. 
$$ \require{mhchem}\ce{NH3-S^* <=> NH3 + S^*} $$
This proposed mechanism is as simple as possible. The final desorbtion step may happen essentially simultaneously with the final $\require{mhchem}\ce{N-H}$ bond formation. We may be able to test this hypothesis with kinetic data or assess under what conditions this assumption might be fair once we have derived a rate equation. But before we derive a rate equation, we should check that the stoichiometry of this series of reactions is equivalent to the complete Haber-Bosch reaction stoichiometry. 

We can also write the above balanced chemical reactions as equations in a similar way to how we made a stoichiometric table which can be helpful in dealing with multiple reactions in parallel or series.

$$\sum_i \nu_i A_i = 0$$ 
where $A_i$ is each chemical species $i$ participating in the reaction, and $\nu_i$ is the stoichiometric coefficient of species *i*. 

We can write the above reactions in this form and then sum these equations to determine the net overall reaction. 

$$\require{mhchem}\ce{ - 3H2 - 6S^* + 6H-S^* = 0} $$
$$ \require{mhchem}\ce{- N2 - 2S^* + 2N-S^* = 0} $$
$$  \require{mhchem}\ce{ - 2N-S^* - 2H-S^* + 2NH-S^* + 2S^* = 0} $$
$$ \require{mhchem}\ce{ - 2NH-S^* - 2H-S^* + 2NH2-S^* + 2S^* = 0} $$
$$ \require{mhchem}\ce{- 2NH2-S^* - 2H-S^* + 2NH3-S^* + 2S^* = 0} $$
$$ \require{mhchem}\ce{- 2NH3-S^* + 2NH3 + 2S^* = 0} $$
We have to multiply these equations to match the stoichiometry of the overall reaction, but in the end you see that the catalyst sites will cancel out along with the other intermediate species yielding the overall net reaction.
$$\require{mhchem}\ce{ - N2 - 3H2 + 2NH3 = 0 }$$

Now that we have a mechanism of elementary reactions that is consistent with the overall reaction, we can write reaction rates for each species in terms of the formation or consumption of that species in each elementary reaction. Then we can solve this set of equations for the rate of the overall reaction in terms of whichever species we'd like. 

